/** Declaration file generated by dts-gen */

export = blake2s;
declare class blake2s {
    constructor(digestLength: any, keyOrConfig: any);
    public digest(): Uint8Array;
    public hexDigest(): string;
    public update(p: Uint8Array, offset?: number, length?: number): blake2s;
    static blockLength: number;
    static digestLength: number;
    static keyLength: number;
    static personalizationLength: number;
    static saltLength: number;
}
